version: 2

project_name: terraform-provider-zabbix

before:
  hooks:
    - go mod tidy

builds:
  - id: terraform-provider-zabbix
    main: .
    binary: terraform-provider-zabbix
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{ .Version }}

archives:
  - id: provider-artifacts
    ids:
      - terraform-provider-zabbix
    formats:
      - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_SHA256SUMS"
  algorithm: sha256

changelog:
  sort: asc

release:
  draft: false
  prerelease: auto
